param([switch]$NoScan)
$ErrorActionPreference="Continue"
function Run-Step($name,$path,[ref]$log){$s=Get-Date; Write-Host "Running $name..." -ForegroundColor Cyan; if(!(Test-Path $path)){return [pscustomobject]@{Name=$name;Status="MISSING";ExitCode="";DurationSec=0}}; $o=& powershell -ExecutionPolicy Bypass -File $path 2>&1; $e=$LASTEXITCODE; $d=[math]::Round(((Get-Date)-$s).TotalSeconds,2); $log.Value += "`n==== $name | Exit=$e | Duration=$d ===="; $log.Value += @($o|%{"$_"}); if($e -eq 0 -or $null -eq $e){Write-Host "OK: $name ($d sec)" -ForegroundColor Green; return [pscustomobject]@{Name=$name;Status="OK";ExitCode="0";DurationSec=$d}} else {Write-Host "ERROR: $name ($e)" -ForegroundColor Red; return [pscustomobject]@{Name=$name;Status="ERROR";ExitCode="$e";DurationSec=$d}}}
$root="C:\Users\crypt\OneDrive\Images\ASTRODDS-workspace"; $astro=Join-Path $root ".astrodds"; $scripts=Join-Path $root "mlb-engine\baseballpred-inspired\scripts"; if(!(Test-Path $astro)){New-Item -ItemType Directory -Force -Path $astro|Out-Null}
$lock=Join-Path $astro "ASTRODDS.prodcore.lock"; if(Test-Path $lock){$age=((Get-Date)-(Get-Item $lock).LastWriteTime).TotalMinutes; if($age -lt 45){Write-Host "Production core already running. Lock age $([math]::Round($age,2)) min." -ForegroundColor Yellow; exit 0}else{Remove-Item $lock -Force}}
"PID=$PID`nStarted=$((Get-Date).ToString('o'))"|Set-Content -Encoding UTF8 $lock
$child=@(); $ref=[ref]$child; $steps=@()
try{$steps += ,(Run-Step "386 DB init" (Join-Path $scripts "386_prod_core_db_init.ps1") $ref); if(-not $NoScan){$steps += ,(Run-Step "338 autopilot scan cycle" (Join-Path $scripts "338_autopilot_server_scan_cycle.ps1") $ref)}; foreach($x in @(@("387 import DB","387_import_latest_artifacts_to_db.ps1"),@("389 clean value report","389_clean_client_value_report.ps1"),@("390 duplicate stale audit","390_duplicate_stale_audit.ps1"),@("391 source health","391_source_health_monitor.ps1"),@("392 regression tests","392_regression_test_suite.ps1"),@("395 prod core report","395_prod_core_report.ps1"))){$steps += ,(Run-Step $x[0] (Join-Path $scripts $x[1]) $ref)}} finally {$child|Set-Content -Encoding UTF8 (Join-Path $astro "ASTRODDS-393-child-log-latest.txt"); if(Test-Path $lock){Remove-Item $lock -Force}}
$lines=@("ASTRODDS 393 PRODUCTION CORE CYCLE","","Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')","","STEPS"); foreach($s in $steps){$lines += "- $($s.Name): $($s.Status) | Exit=$($s.ExitCode) | Duration=$($s.DurationSec)s"}; foreach($f in @("ASTRODDS-389-clean-client-value-report-latest.txt","ASTRODDS-390-duplicate-stale-audit-latest.txt","ASTRODDS-391-source-health-monitor-latest.txt","ASTRODDS-392-regression-test-suite-latest.txt")){$lines += "`n===== $f ====="; $p=Join-Path $astro $f; if(Test-Path $p){$lines += Get-Content $p -Raw}else{$lines += "MISSING"}}
$lines|Set-Content -Encoding UTF8 (Join-Path $astro "ASTRODDS-393-prod-core-cycle-latest.txt"); Write-Host ($lines -join [Environment]::NewLine); exit 0
